In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('../datasets/non_pca_weather_scores_w_avgs.csv')
df

,schedule_date,schedule_season,home_id,away_id,weather_temperature,weather_wind_mph,score_home,home_avg_first_downs,home_avg_yds,home_avg_pass_yds,...,score_away,away_avg_first_downs,away_avg_yds,away_avg_pass_yds,away_avg_rush_yds,away_avg_TO,total_score,over_under_line,label,encoded_label
0,1/14/1968,1967,GNB,RAI,60.0,12.0,33,17.647059,304.117647,167.764706,...,14,17.764706,361.764706,218.705882,143.058824,2.352941,47,43.0,over,-1
1,1/12/1969,1968,CLT,NYJ,66.0,12.0,7,18.411765,332.529412,203.941176,...,16,18.705882,365.470588,247.411765,118.058824,1.823529,23,40.0,under,1
2,1/11/1970,1969,KAN,MIN,55.0,14.0,23,17.823529,315.470588,165.117647,...,7,16.941176,293.705882,162.176471,131.529412,2.235294,30,39.0,under,1
3,1/17/1971,1970,CLT,DAL,59.0,11.0,16,17.058824,301.470588,201.411765,...,13,16.117647,306.823529,139.647059,167.176471,2.000000,29,36.0,under,1
4,1/16/1972,1971,DAL,MIA,34.0,18.0,24,19.823529,342.000000,179.000000,...,3,16.294118,311.176471,146.647059,164.529412,1.705882,27,34.0,under,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9682,12/27/2020,2020,HTX,CIN,72.0,0.0,31,20.117647,373.470588,279.058824,...,37,20.882353,336.000000,232.529412,103.470588,1.411765,68,46.0,over,-1
9683,1/3/2021,2020,DET,MIN,72.0,0.0,35,21.588235,347.529412,249.294118,...,37,22.941176,378.764706,243.235294,135.529412,1.470588,72,53.5,over,-1
9684,1/3/2021,2020,HTX,OTI,72.0,0.0,38,20.529412,379.176471,287.411765,...,41,23.588235,390.470588,227.235294,163.235294,0.705882,79,55.5,over,-1
9685,1/3/2021,2020,CLT,JAX,72.0,0.0,28,22.411765,372.000000,246.823529,...,14,19.588235,327.705882,234.411765,93.294118,1.529412,42,48.0,under,1
9686,2/7/2021,2020,TAM,KAN,63.0,9.0,31,23.235294,391.588235,289.647059,...,9,24.764706,417.470588,308.529412,108.941176,1.176471,40,54.5,under,1

In [3]:
cols = ['weather_temperature', 'weather_wind_mph', 'home_avg_first_downs', 'home_avg_yds', 'home_avg_pass_yds', 'home_avg_rush_yds', 'home_avg_TO', 'away_avg_first_downs', 'away_avg_yds', 'away_avg_pass_yds', 'away_avg_rush_yds', 'away_avg_TO']
features = df[cols]
features
features = StandardScaler().fit_transform(features)
features

array([[ 0.00626697,  0.82518334, -0.59174013, ...,  0.18693986,
         1.3754396 ,  0.92094221],
       [ 0.39542157,  0.82518334, -0.23620141, ...,  0.96843863,
         0.14057424, -0.12793504],
       [-0.31802853,  1.17433056, -0.50969273, ..., -1.3520362 ,
         0.80594875,  0.68785838],
       ...,
       [ 0.78457617, -1.26969998,  0.74836734, ...,  0.41914748,
         2.37204858, -2.34223146],
       [ 0.78457617, -1.26969998,  1.62353957, ...,  0.61452217,
        -1.08266885, -0.71064462],
       [ 0.20084427,  0.30146251,  2.00642742, ...,  2.63232637,
        -0.30978842, -1.40989612]])

In [4]:
labels = np.ravel(df['encoded_label'])
labels

array([-1,  1,  1, ..., -1,  1,  1], dtype=int64)

In [7]:
from sklearn.model_selection import cross_validate
svc = SVC(kernel='linear', C=0.7)


cv_results = cross_validate(svc, features, labels, cv=10, scoring=('accuracy', 'precision', 'recall', 'f1'))

del cv_results['score_time']
del cv_results['fit_time']

In [8]:
for metric_name, values in cv_results.items():
    print(f'Metric: {metric_name}')
    #for val in values:
    #    print(f'\t{val}')
    print(f'\tMean: {100 * np.mean(values)}')
    print(f'\tStandard Deviation: {100 * np.std(values)}')

Metric: test_accuracy
	Mean: 52.090199063531465
	Standard Deviation: 0.7041995933762731
Metric: test_precision
	Mean: 52.771895342473584
	Standard Deviation: 0.5115303554889425
Metric: test_recall
	Mean: 67.8373614699278
	Standard Deviation: 14.592557396733646
Metric: test_f1
	Mean: 58.579544854703435
	Standard Deviation: 6.033984673243598

In [11]:
svc = SVC(kernel='poly', C=0.4)


cv_results = cross_validate(svc, features, labels, cv=10, scoring=('accuracy', 'precision', 'recall', 'f1'))

del cv_results['score_time']
del cv_results['fit_time']

In [12]:
for metric_name, values in cv_results.items():
    print(f'Metric: {metric_name}')
    #for val in values:
    #    print(f'\t{val}')
    print(f'\tMean: {100 * np.mean(values)}')
    print(f'\tStandard Deviation: {100 * np.std(values)}')

Metric: test_accuracy
	Mean: 52.85478980630964
	Standard Deviation: 1.2645521519257226
Metric: test_precision
	Mean: 52.680250996126546
	Standard Deviation: 1.0064343570172714
Metric: test_recall
	Mean: 85.5626111661073
	Standard Deviation: 7.693752902568109
Metric: test_f1
	Mean: 65.0382953190009
	Standard Deviation: 1.7851317576180563

In [13]:
svc = SVC(kernel='rbf', C=0.1)


cv_results = cross_validate(svc, features, labels, cv=10, scoring=('accuracy', 'precision', 'recall', 'f1'))

del cv_results['score_time']
del cv_results['fit_time']

In [15]:
for metric_name, values in cv_results.items():
    print(f'Metric: {metric_name}')
    #for val in values:
    #    print(f'\t{val}')
    print(f'\tMean: {100 * np.mean(values)}')
    print(f'\tStandard Deviation: {100 * np.std(values)}')

Metric: test_accuracy
	Mean: 52.16277963991164
	Standard Deviation: 0.9092539084686234
Metric: test_precision
	Mean: 52.80890237425414
	Standard Deviation: 1.0434746868870541
Metric: test_recall
	Mean: 71.92606095725587
	Standard Deviation: 16.881906835772607
Metric: test_f1
	Mean: 59.85500752929315
	Standard Deviation: 6.407296518183234